version: '3.9'

services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    restart: unless-stopped
    command: mongod --port ${DB_PORT}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./.build/volumes/mongodb/data:/data/db
    env_file:
      - .env
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - application

  mongo-express:
    image: mongo-express
    container_name: "mongo-express"
    depends_on:
      - mongodb
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_AUTH_USERNAME: ${DB_USER}
      ME_CONFIG_MONGODB_AUTH_PASSWORD: ${DB_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/
    env_file:
      - .env
    networks:
      - application

networks:
  application:
    driver: bridge